baseURL = 'https://krogowski.dev/'
languageCode = 'en-us'
title = 'Kacper Rogowski'
theme = 'rogemus'
description = 'Hi, I’m Kacper. And this is my website. You should totally check it out.'

[markup]
[markup.highlight]
lineNos = true

[params]
title = 'Kacper Rogowski'
description = 'Hi, I’m Kacper. And this is my website. You should totally check it out.'
keywords = "front-end, frontend, developer, react, typescipt, javascript, html, css"
images = ["/social-cover.png"]

[params.social]
twitter = "rogemus"

[params.author]
name = "Kacper Rogowski"
homepage = "https://www.krogowski.dev/"

[params.aboutme]
name = 'Kacper Rogowski'
position = 'Front-end Developer'
location = 'Gdańsk, PL'
about = """
Experienced **React** and **Javascript**, **Typescript** developer with strong frontend skills.
Ambitious to evolve into a Full Stack Developer. Committed to success with a mindset of "_everything is possible, it's just a matter of when_".
"""

[params.menu]
[params.menu.resume]
title = "CV / Resume"
name = "resume"
link = "https://1drv.ms/b/c/77b8fa8c85613934/EXq4RA3YZllEqQz0z7zyPk0B1vtdTi3Jyeyb-om34jX92g?e=IujWy4"
icon = "icons/zap"
order = 1

# [params.menu.post]
# title = "Recent Posts"
# name = "recent-posts"
# link = "#posts"
# icon = "icons/bookmark"
# order = 2

[params.menu.stack]
title = "Stack"
name = "stack"
link = "#stack"
icon = "icons/layers"
order = 3

[params.menu.contact]
title = "Contact"
name = "contact"
link = "#contact"
icon = "icons/atsign"
order = 4


[params.contact]
# [params.contact.resume]
# title = "CV / Resume"
# label = "@onedrive"
# name = "resume"
# link = "https://1drv.ms/b/c/77b8fa8c85613934/EXq4RA3YZllEqQz0z7zyPk0B1vtdTi3Jyeyb-om34jX92g?e=IujWy4"
# order = 1

[params.contact.linkedin]
title = "Linkedin"
label = "@kacper-rogowski"
name = "linkedin"
link = "https://www.linkedin.com/in/kacper-rogowski/"
order = 2

[params.contact.mail]
title = "Email"
label = "kacper.rogowski@outlook.com"
name = "mail"
link = "mailto:kacper.rogowski@outlook.com"
order = 3

[params.contact.github]
title = "Github"
label = "@rogemus"
name = "github"
link = "https://github.com/rogemus"
order = 4

[params.stack]
[params.stack.react]
icon = "icons/react"
name = "react"
link = ""
title = "React"
subtitle = "Frontend lib"
order = 1

[params.stack.ts]
icon = "icons/ts"
name = "typescipt"
link = "https://www.typescriptlang.org"
title = "TypeScript"
subtitle = "Programing language"
order = 2

[params.stack.go]
icon = "icons/golang"
name = "go"
link = "https://go.dev"
title = "Go"
subtitle = "Programing language"
order = 4

[params.stack.github]
icon = "icons/github"
name = "github"
link = "https://github.com/rogemus"
title = "Github"
subtitle = "Dev Tool"
order = 5

[params.stack.figma]
icon = "icons/figma"
name = "figma"
link = "https://www.figma.com"
title = "Figma"
subtitle = "Design Tool"
order = 6

[params.stack.neovim]
icon = "icons/code"
name = "neovim"
link = "https://neovim.io/"
title = "NeoVim"
subtitle = "Code Editor"
order = 7

